apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aws-localstack
  name: aws-localstack
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aws-localstack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aws-localstack
    spec:
      containers:
      #- image: atlassianlabs/localstack
      #- image: localstack/localstack
      - image: atlassianlabs/localstack
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-volume-1
          mountPath: /tmp/localstack
        name: localstack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: DATA_DIR
            value: /tmp/localstack/data
          - name: Version
            value: AlphaV1.0
      volumes:
      - name: nfs-volume-1
        persistentVolumeClaim:
          claimName: nfs-pvc
          readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
# creationTimestamp: "2021-01-24T04:41:05Z"
  labels:
    app: aws-localstack
  name: aws-localstack
  namespace: default
#  resourceVersion: "4168525"
#  selfLink: /api/v1/namespaces/default/services/aws-localstack
#  uid: 3b09fdf0-5fdf-42fe-b3ef-feab41fe9084
spec:
#  clusterIP: 10.3.245.100
  ports:
  # was 4572
  - port: 4572
    name: storage
    protocol: TCP
    targetPort: 4572
  # was 4568
  - port: 4568
    name: kenesis
    protocol: TCP
    targetPort: 4568
  - port: 8080
    name: dashboard
    protocol: TCP
    targetPort: 8080
  selector:
    app: aws-localstack
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
